# Generated by Django 6.0.3 on 2026-06-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COL_Column',
            fields=[
                ('COL_id', models.AutoField(primary_key=True, serialize=False)),
                ('COL_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DYT_DynamicTable',
            fields=[
                ('DYT_id', models.AutoField(primary_key=True, serialize=False)),
                ('DYT_name', models.CharField(max_length=30)),
                ('DYT_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TD_TypeData',
            fields=[
                ('TD_id', models.AutoField(primary_key=True, serialize=False)),
                ('TD_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CEL_Cell',
            fields=[
                ('CEL_id', models.AutoField(primary_key=True, serialize=False)),
                ('CEL_value', models.CharField(max_length=30)),
                ('COL_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.col_column')),
            ],
        ),
        migrations.AddField(
            model_name='col_column',
            name='DYT_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.dyt_dynamictable'),
        ),
        migrations.CreateModel(
            name='TAG_TagOption',
            fields=[
                ('TAG_id', models.AutoField(primary_key=True, serialize=False)),
                ('TAG_value', models.CharField(max_length=30)),
                ('TAG_color', models.CharField(max_length=8)),
                ('COL_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.col_column')),
            ],
        ),
    ]
